version: "3.9"

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: bexup-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "16453:80"
